auth.py
from flask import Blueprint, render_template, request, redirect, url_for, Response, flash
import requests
from flask import make_response
import json  # подключили библиотеку для работы с json
from pprint import pprint  # подключили Pprint для красоты выдачи текста

auth_func = Blueprint('auth_func', __name__)
# global Permission_SeeAllObjects
# global podved_code


@auth_func.route('/signout')
def signout():
    print('удаляем токены')
    response = make_response(redirect(url_for('auth_func.login')))
    response.delete_cookie('access_token')
    response.delete_cookie('refresh_token')
    response.delete_cookie('username_token')

    # возвращаем измененный ответ
    return response


@auth_func.route('/login', methods=['GET', 'POST'])
def login(refresh_token=None):
    # refr = request.cookies.get('refresh_token')
    # if request.cookies.get('refresh_token') != None:
    #
    #     return makeAccesToken()
    if request.cookies.get('access_token') and request.cookies.get('refresh_token'):
        valid = validateAccesToken()
        if valid == 'True':
            flash('Вы уже авторизованы')
            return redirect(url_for('podved', id = '1'))
    elif request.cookies.get('refresh_token') and not request.cookies.get('access_token'):
        return makeAccesToken()

    # если нет ни токена рефреш ни акцес
    elif not request.cookies.get('refresh_token') and not request.cookies.get('access_token'):
        if request.method == 'POST':
            login = request.form.get('username')
            password = request.form.get('password')
            param_request = {'login': login, 'password': password}
            response_cookie = requests.post("https://localhost/copy_1/hs/HTTP_SERVER/Auth20", data=param_request,
                                            verify=False)
            if response_cookie.status_code == 200:
                print('Success!')
            elif response_cookie.status_code == 401:
                print('Not auth.')
            success = response_cookie.json()['success']
            blockuser = response_cookie.json()['blockuser']
            refresh_token = response_cookie.json()['RefreshToken']
            # print(success, blockuser)
            print(response_cookie.json())
            if success == True and blockuser == False:
                return makeRefreshToken(refresh_token)
            else:
                flash('Пожалуйста проверьте правильность логина и пароля')
                return render_template('login.html', title='Авторизация')

    return render_template('login.html', title='Авторизация')


def login_api(getlogin,password):
    getlogin = getlogin
    password = password
    param_request = {'login': getlogin, 'password': password}
    response_cookie = requests.post("https://localhost/copy_1/hs/HTTP_SERVER/Auth20", data=param_request,
                                    verify=False)
    if response_cookie.status_code == 200:
        print('Success!')
    elif response_cookie.status_code == 401:
        print('Not auth.')
    # success = response_cookie.json()['success']
    # blockuser = response_cookie.json()['blockuser']
    # refresh_token = response_cookie.json()['RefreshToken']
    # # print(success, blockuser)
    # print(response_cookie.json())
    return response_cookie.json()


def accessTokenApi(refresh_token):
    print('судьба вас примвела в AccesToken')
    refresh = refresh_token
    param_request = {'RefreshToken': refresh}
    response = requests.post("https://localhost/copy_1/hs/HTTP_SERVER/Auth20", data=param_request,
                             verify=False)
    return response.json()

def validateAccesTokenApi(access_token):

    access = access_token
    param_request = {'AccessToken': access}
    response = requests.post("https://localhost/copy_1/hs/HTTP_SERVER/Auth20", data=param_request,
                             verify=False)
    print(response.json())
    return response.json()



def getPodved():
    podved = podved_code
    permission_see = Permission_SeeAllObjects
    print(podved, permission_see)
    return (podved, permission_see)


def getPermissions():
    allpermissionmenu = allpermissions
    Permission_SeeDepartments = allpermissionmenu['Permission_SeeDepartments']
    Permission_SeeCategoryPodved = allpermissionmenu['Permission_SeeCategoryPodved']
    context = {'Permission_SeeCategoryPodved':Permission_SeeCategoryPodved, 'Permission_SeeDepartments':Permission_SeeDepartments}
    return (context)

def updatePodvedInfo():
    allpermissionmenu = allpermissions
    need_confirm_contacts = allpermissionmenu['need_confirm_contacts']
    print('updatePodvedInfo проверка')
    print(need_confirm_contacts)
    return need_confirm_contacts

#
def makeRefreshToken(refresh_token):
    print('судьба вас примвела в makeRefreshToken')
    response = make_response(redirect(url_for('auth_func.login')))
    response.set_cookie('refresh_token', refresh_token, samesite='Lax', max_age=30 * 24 * 3600)
    return response


def makeAccesToken():
    print('судьба вас примвела в makeAccesToken')
    refresh_token = request.cookies.get('refresh_token')
    print(refresh_token)
    param_request = {'RefreshToken': refresh_token}
    response = requests.post("https://localhost/copy_1/hs/HTTP_SERVER/Auth20", data=param_request,
                             verify=False)
    access_token = response.json()['AccessToken']
    username_token = response.json()['UserName']
    success = response.json()['success']
    blockuser = response.json()['blockuser']
    print("response.text:\n{}\n\n".format(response.text))
    if success == True and blockuser == False:
        print('dsvdsvd1')
        response = make_response(redirect(url_for('podved', id='1')))
        response.set_cookie('access_token', access_token, samesite='Lax', max_age=86400)
        response.set_cookie('username_token', username_token, samesite='Lax', max_age=86400)
        return response
    elif success == False and blockuser == False:
        return 'вы не имеете права'


def refreshAccesToken(link_send_to_refresh):
    print(link_send_to_refresh)
    print('судьба вас примвела в refreshAccesToken')
    refresh_token = request.cookies.get('refresh_token')
    # print(refresh_token)
    param_request = {'RefreshToken': refresh_token}
    response = requests.post("https://localhost/copy_1/hs/HTTP_SERVER/Auth20", data=param_request,
                             verify=False)
    access_token = response.json()['AccessToken']
    username_token = response.json()['UserName']
    # print(access_token)
    success = response.json()['success']
    blockuser = response.json()['blockuser']
    # print("response.text:\n{}\n\n".format(response.text))
    link = link_send_to_refresh.get('link')
    id = link_send_to_refresh.get('id')
    print("response.text:\n{}\n\n".format(response.text))
    print(id)
    if success == True and blockuser == False:
        if id == None:
            response = make_response(redirect(url_for(link, id='1')))
            print('response')
            response.set_cookie('access_token', access_token, samesite='Lax', max_age=86400)
            response.set_cookie('username_token', username_token, samesite='Lax', max_age=86400)
            print('dsvdsvd if')
            return response
        else:
            response = make_response(redirect(url_for(link, id=id)))
            print('response')
            response.set_cookie('access_token', access_token, samesite='Lax', max_age=86400)
            response.set_cookie('username_token', username_token, samesite='Lax', max_age=86400)
            print('dsvdsvd if')
            return response
    elif success == False and blockuser == False:
        return deleteTokens()


def validateAccesToken():
    global podved_code
    global Permission_SeeAllObjects
    global allpermissions
    access_token = request.cookies.get('access_token')
    param_request = {'AccessToken': access_token}
    response = requests.post("https://localhost/copy_1/hs/HTTP_SERVER/Auth20", data=param_request,
                             verify=False)
    success = response.json()['success']
    blockuser = response.json()['blockuser']
    allpermissions = response.json()
    token_expired = response.json()['AccessTokenTokenExpired']
    try:
        Permission_SeeAllObjects = response.json()['Permission_SeeAllObjects']
        podved_code = response.json()['podved_code']
    except:
        print('podved_code and permission false')
        return 'False'
    print(podved_code, Permission_SeeAllObjects)
    print('test validateAccesToken:', success, blockuser, token_expired, access_token)
    print("response.text:\n{}\n\n".format(response.text))
    if success == True and blockuser == False and token_expired == False:
        # if podved_code == '' and Permission_SeeAllObjects =='':
        #     return 'False'
        # else:
        return 'True'

    elif success == True and blockuser == False and token_expired == True:
        return refreshAccesToken()
    elif success == False and blockuser == False and token_expired == False:
        print('валидацию не прошел')
        return deleteTokens()


def getAccessToken():
    access_token = request.cookies.get('access_token')
    print(access_token)
    return access_token


def deleteTokens():
    print('удаляем токены')
    response = make_response(redirect(url_for('auth_func.login')))
    response.delete_cookie('access_token')
    response.delete_cookie('refresh_token')
    response.delete_cookie('username_token')
    # возвращаем измененный ответ
    return response

templates/basic/basic2.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    {% if title %}
    <title>Министерство культуры - {{ title }}</title>
    {% else %}
    <title>Министерство культуры</title>
    {% endif %}
    {% endblock %}
{#  <link#}
{#  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"#}
{#  rel="stylesheet"#}
{#/>#}
{#<!-- Google Fonts -->#}
{#<link#}
{#  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"#}
{#  rel="stylesheet"#}
{#/>#}
{#<!-- MDB -->#}
{#<link#}
{#  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css"#}
{#  rel="stylesheet"#}
{#/>#}
{#  <!-- MDB -->#}
{#<script#}
{#  type="text/javascript"#}
{#  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"#}
{#></script>#}
    <link type="text/css" href="{{ url_for('static', filename='1cintegr/css/style.css') }}" rel="stylesheet">
{#  <link type="text/css" href="{{ url_for('static', filename='1cintegr/css/custom.css') }}" rel="stylesheet">#}
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </head>
<body>
<div class="wrapper">

    <div class="header">
        <a href="{{ url_for('podved') }}"><img class="logo justify-content-start" alt="Logo" src="/static/1cintegr/img/min_kult.svg"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Offcanvas</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.
    </div>
    <div class="dropdown mt-3">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown">
        Dropdown button
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
      </ul>
    </div>
  </div>
</div>
    <nav class="nav_bar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
            <ul class="list-group list-group-flush paddingtop-3">
                <li class="list-group-item d-grid gap-2 "><a href="{{ url_for('documents') }}"><button id="home" type="button" class="btn border-0 btn-light col-12 text-start shadow-none"><div class="boxmin"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="makeStyles-icon-1640"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg></div><div class="boxmin2">Подведомственные организации</div></button></a></li>
                <li class="list-group-item d-grid gap-2"><a href="{{ url_for('category') }}"><button id="category" type="button" class="btn border-0 btn-light col-12 text-start shadow-none"><div class="boxmin"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="makeStyles-icon-1610"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg></div><div class="boxmin2">Категория подведомственной организации</div></button></a></li>
                <li class="list-group-item d-grid gap-2"><a href=""><button id="objects" type="button" class="btn border-0 btn-light col-12 text-start shadow-none"><div class="boxmin"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="makeStyles-icon-1640"><ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"></path><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"></path></svg></div><div class="boxmin2"> Объекты недвижимости</div></button></a></li>
                <li class="list-group-item d-grid gap-2"><a href="{{ url_for('search') }}"><button id="search" type="button" class="btn border-0 btn-light col-12 text-start shadow-none"><div class="boxmin"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="makeStyles-icon-1640"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg></div><div class="boxmin2"> Поиск</div></button></a></li>
            </ul>

    </nav>

    <div class="content">
            <div class="container-xxl rounded spacing bgnd-white border border-grey overflow-auto">

            {% block content %}
                {#        #}
            {% endblock %}
            </div>

    </div>
</div>
</body>
</html>

templates/basic/redirectpodved.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Добавление информации.</title>
    <link type="text/css" href="{{ url_for('static', filename='1cintegr/css/style.css') }}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    {#<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <nav class="header navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <a href=""><img class="logo justify-content-start" alt="Logo"
                                                   src="/static/1cintegr/img/min_kult_resurs.svg"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex justify-content-end col-7">Пользователь: {{ getusername }}</div>

            <div class="text-center"><a href="{{ url_for('auth_func.signout') }}"
                                        class="btn btn-link border-0 col-12 text-start shadow-none fw-semibold text-secondary"
                                        role="button">
                <svg class="MuiSvgIcon-root" fill="white" width="20" height="20" focusable="false" viewBox="0 0 24 24"
                     aria-hidden="true">
                    <path d="M21 3.01H3c-1.1 0-2 .9-2 2V9h2V4.99h18v14.03H3V15H1v4.01c0 1.1.9 1.98 2 1.98h18c1.1 0 2-.88 2-1.98v-14c0-1.11-.9-2-2-2zM11 16l4-4-4-4v3H1v2h10v3z"></path>
                </svg>
            </a></div>
        </div>
    </nav>
  <div class="row justify-content-center">
    <div class="col-4">
      <form method="POST" enctype="multipart/form-data">
  <div class="col-auto">
     <h1 class="display-5">Для того что бы работать с порталом вы должны указать недостающую информацию.</h1>
    <label for="contact_name">Ответственное лицо</label>
    <input type="text"  class="form-control" id="contact_name" name="contact_name" placeholder="Ответственное лицо">
  </div>
  <div class="col-auto mt-3">
    <label for="contact_phone">Телефон ответственного лица</label>
    <input type="text" class="form-control" id="contact_phone" name="contact_phone" placeholder="Телефон ответственного лица">
  </div><div class="col-auto mt-3">
    <label for="supervisor_name">Руководитель ответственного лица</label>
    <input type="text"  class="form-control" id="supervisor_name" name="supervisor_name" placeholder="Руководитель ответственного лица">
  </div>
  <div class="col-auto mt-3">
    <label for="supervisor_phone">Телефон руководителя ответственного лица</label>
    <input type="text" class="form-control" id="supervisor_phone" name="supervisor_phone" placeholder="Телефон ответственного лица">
  </div>
  <div class="col-auto mt-3">
    <button type="submit" class="btn btn-primary mb-3">Подтвердить </button>
  </div>
</form>
    </div>

  </div>

</body>
</html>